// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Usermanager.Model.DBContext;

#nullable disable

namespace Usermanager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GroupRole", b =>
                {
                    b.Property<int>("GroupsId")
                        .HasColumnType("int");

                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.HasKey("GroupsId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("GroupRole");
                });

            modelBuilder.Entity("Usermanager.Model.Entity.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "تهران",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "ری",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "دماوند",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "پردیس",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "ورامین",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "شهریار",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "اسلام‌شهر",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "ملارد",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "پاکدشت",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 10,
                            Name = "کرج",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 11,
                            Name = "نظرآباد",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 12,
                            Name = "طالقان",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 13,
                            Name = "اشتهارد",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 14,
                            Name = "فردیس",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 15,
                            Name = "اصفهان",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 16,
                            Name = "کاشان",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 17,
                            Name = "خمینی‌شهر",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 18,
                            Name = "نجف‌آباد",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 19,
                            Name = "شهرضا",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 20,
                            Name = "فلاورجان",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 21,
                            Name = "مبارکه",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 22,
                            Name = "شیراز",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 23,
                            Name = "مرودشت",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 24,
                            Name = "جهرم",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 25,
                            Name = "لار",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 26,
                            Name = "فسا",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 27,
                            Name = "کازرون",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 28,
                            Name = "داراب",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 29,
                            Name = "مشهد",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 30,
                            Name = "نیشابور",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 31,
                            Name = "سبزوار",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 32,
                            Name = "تربت‌حیدریه",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 33,
                            Name = "قوچان",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 34,
                            Name = "چناران",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 35,
                            Name = "تبریز",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 36,
                            Name = "مراغه",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 37,
                            Name = "مرند",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 38,
                            Name = "میانه",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 39,
                            Name = "اهر",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 40,
                            Name = "بناب",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 41,
                            Name = "ارومیه",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 42,
                            Name = "خوی",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 43,
                            Name = "بوکان",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 44,
                            Name = "مهاباد",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 45,
                            Name = "سلماس",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 46,
                            Name = "میاندوآب",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 47,
                            Name = "رشت",
                            ProvinceId = 8
                        },
                        new
                        {
                            Id = 48,
                            Name = "لاهیجان",
                            ProvinceId = 8
                        },
                        new
                        {
                            Id = 49,
                            Name = "انزلی",
                            ProvinceId = 8
                        },
                        new
                        {
                            Id = 50,
                            Name = "آستارا",
                            ProvinceId = 8
                        },
                        new
                        {
                            Id = 51,
                            Name = "تالش",
                            ProvinceId = 8
                        },
                        new
                        {
                            Id = 52,
                            Name = "صومعه‌سرا",
                            ProvinceId = 8
                        },
                        new
                        {
                            Id = 53,
                            Name = "ساری",
                            ProvinceId = 9
                        },
                        new
                        {
                            Id = 54,
                            Name = "بابل",
                            ProvinceId = 9
                        },
                        new
                        {
                            Id = 55,
                            Name = "آمل",
                            ProvinceId = 9
                        },
                        new
                        {
                            Id = 56,
                            Name = "نور",
                            ProvinceId = 9
                        },
                        new
                        {
                            Id = 57,
                            Name = "تنکابن",
                            ProvinceId = 9
                        },
                        new
                        {
                            Id = 58,
                            Name = "قائم‌شهر",
                            ProvinceId = 9
                        },
                        new
                        {
                            Id = 59,
                            Name = "کرمان",
                            ProvinceId = 10
                        },
                        new
                        {
                            Id = 60,
                            Name = "رفسنجان",
                            ProvinceId = 10
                        },
                        new
                        {
                            Id = 61,
                            Name = "جیرفت",
                            ProvinceId = 10
                        },
                        new
                        {
                            Id = 62,
                            Name = "سیرجان",
                            ProvinceId = 10
                        },
                        new
                        {
                            Id = 63,
                            Name = "بم",
                            ProvinceId = 10
                        },
                        new
                        {
                            Id = 64,
                            Name = "بندرعباس",
                            ProvinceId = 11
                        },
                        new
                        {
                            Id = 65,
                            Name = "قشم",
                            ProvinceId = 11
                        },
                        new
                        {
                            Id = 66,
                            Name = "بندر لنگه",
                            ProvinceId = 11
                        },
                        new
                        {
                            Id = 67,
                            Name = "میناب",
                            ProvinceId = 11
                        },
                        new
                        {
                            Id = 68,
                            Name = "حاجی‌آباد",
                            ProvinceId = 11
                        },
                        new
                        {
                            Id = 69,
                            Name = "اهواز",
                            ProvinceId = 12
                        },
                        new
                        {
                            Id = 70,
                            Name = "آبادان",
                            ProvinceId = 12
                        },
                        new
                        {
                            Id = 71,
                            Name = "خرمشهر",
                            ProvinceId = 12
                        },
                        new
                        {
                            Id = 72,
                            Name = "دزفول",
                            ProvinceId = 12
                        },
                        new
                        {
                            Id = 73,
                            Name = "ماهشهر",
                            ProvinceId = 12
                        },
                        new
                        {
                            Id = 74,
                            Name = "شادگان",
                            ProvinceId = 12
                        },
                        new
                        {
                            Id = 75,
                            Name = "سنندج",
                            ProvinceId = 13
                        },
                        new
                        {
                            Id = 76,
                            Name = "سقز",
                            ProvinceId = 13
                        },
                        new
                        {
                            Id = 77,
                            Name = "بانه",
                            ProvinceId = 13
                        },
                        new
                        {
                            Id = 78,
                            Name = "بیجار",
                            ProvinceId = 13
                        },
                        new
                        {
                            Id = 79,
                            Name = "قروه",
                            ProvinceId = 13
                        },
                        new
                        {
                            Id = 80,
                            Name = "کرمانشاه",
                            ProvinceId = 14
                        },
                        new
                        {
                            Id = 81,
                            Name = "اسلام‌آباد غرب",
                            ProvinceId = 14
                        },
                        new
                        {
                            Id = 82,
                            Name = "سرپل ذهاب",
                            ProvinceId = 14
                        },
                        new
                        {
                            Id = 83,
                            Name = "قصر شیرین",
                            ProvinceId = 14
                        },
                        new
                        {
                            Id = 84,
                            Name = "سنقر",
                            ProvinceId = 14
                        },
                        new
                        {
                            Id = 85,
                            Name = "یزد",
                            ProvinceId = 15
                        },
                        new
                        {
                            Id = 86,
                            Name = "میبد",
                            ProvinceId = 15
                        },
                        new
                        {
                            Id = 87,
                            Name = "اردکان",
                            ProvinceId = 15
                        },
                        new
                        {
                            Id = 88,
                            Name = "ابرکوه",
                            ProvinceId = 15
                        },
                        new
                        {
                            Id = 89,
                            Name = "تفت",
                            ProvinceId = 15
                        },
                        new
                        {
                            Id = 90,
                            Name = "زنجان",
                            ProvinceId = 16
                        },
                        new
                        {
                            Id = 91,
                            Name = "ابهر",
                            ProvinceId = 16
                        },
                        new
                        {
                            Id = 92,
                            Name = "خرمدره",
                            ProvinceId = 16
                        },
                        new
                        {
                            Id = 93,
                            Name = "طارم",
                            ProvinceId = 16
                        },
                        new
                        {
                            Id = 94,
                            Name = "ماه‌نشان",
                            ProvinceId = 16
                        },
                        new
                        {
                            Id = 95,
                            Name = "همدان",
                            ProvinceId = 17
                        },
                        new
                        {
                            Id = 96,
                            Name = "ملایر",
                            ProvinceId = 17
                        },
                        new
                        {
                            Id = 97,
                            Name = "نهاوند",
                            ProvinceId = 17
                        },
                        new
                        {
                            Id = 98,
                            Name = "تویسرکان",
                            ProvinceId = 17
                        },
                        new
                        {
                            Id = 99,
                            Name = "رزن",
                            ProvinceId = 17
                        },
                        new
                        {
                            Id = 100,
                            Name = "قزوین",
                            ProvinceId = 18
                        },
                        new
                        {
                            Id = 101,
                            Name = "الوند",
                            ProvinceId = 18
                        },
                        new
                        {
                            Id = 102,
                            Name = "آبیک",
                            ProvinceId = 18
                        },
                        new
                        {
                            Id = 103,
                            Name = "تاکستان",
                            ProvinceId = 18
                        },
                        new
                        {
                            Id = 104,
                            Name = "قم",
                            ProvinceId = 19
                        },
                        new
                        {
                            Id = 105,
                            Name = "سمنان",
                            ProvinceId = 20
                        },
                        new
                        {
                            Id = 106,
                            Name = "شاهرود",
                            ProvinceId = 20
                        },
                        new
                        {
                            Id = 107,
                            Name = "دامغان",
                            ProvinceId = 20
                        },
                        new
                        {
                            Id = 108,
                            Name = "گرمسار",
                            ProvinceId = 20
                        },
                        new
                        {
                            Id = 109,
                            Name = "ایلام",
                            ProvinceId = 21
                        },
                        new
                        {
                            Id = 110,
                            Name = "دهلران",
                            ProvinceId = 21
                        },
                        new
                        {
                            Id = 111,
                            Name = "مهران",
                            ProvinceId = 21
                        },
                        new
                        {
                            Id = 112,
                            Name = "آبدانان",
                            ProvinceId = 21
                        },
                        new
                        {
                            Id = 113,
                            Name = "یاسوج",
                            ProvinceId = 22
                        },
                        new
                        {
                            Id = 114,
                            Name = "گچساران",
                            ProvinceId = 22
                        },
                        new
                        {
                            Id = 115,
                            Name = "دهدشت",
                            ProvinceId = 22
                        },
                        new
                        {
                            Id = 116,
                            Name = "شهرکرد",
                            ProvinceId = 23
                        },
                        new
                        {
                            Id = 117,
                            Name = "فارسان",
                            ProvinceId = 23
                        },
                        new
                        {
                            Id = 118,
                            Name = "بروجن",
                            ProvinceId = 23
                        },
                        new
                        {
                            Id = 119,
                            Name = "لردگان",
                            ProvinceId = 23
                        },
                        new
                        {
                            Id = 120,
                            Name = "خرم‌آباد",
                            ProvinceId = 24
                        },
                        new
                        {
                            Id = 121,
                            Name = "بروجرد",
                            ProvinceId = 24
                        },
                        new
                        {
                            Id = 122,
                            Name = "دورود",
                            ProvinceId = 24
                        },
                        new
                        {
                            Id = 123,
                            Name = "الیگودرز",
                            ProvinceId = 24
                        },
                        new
                        {
                            Id = 124,
                            Name = "اراک",
                            ProvinceId = 25
                        },
                        new
                        {
                            Id = 125,
                            Name = "ساوه",
                            ProvinceId = 25
                        },
                        new
                        {
                            Id = 126,
                            Name = "خمین",
                            ProvinceId = 25
                        },
                        new
                        {
                            Id = 127,
                            Name = "محلات",
                            ProvinceId = 25
                        },
                        new
                        {
                            Id = 128,
                            Name = "بوشهر",
                            ProvinceId = 26
                        },
                        new
                        {
                            Id = 129,
                            Name = "برازجان",
                            ProvinceId = 26
                        },
                        new
                        {
                            Id = 130,
                            Name = "جم",
                            ProvinceId = 26
                        },
                        new
                        {
                            Id = 131,
                            Name = "دیر",
                            ProvinceId = 26
                        },
                        new
                        {
                            Id = 132,
                            Name = "کنگان",
                            ProvinceId = 26
                        },
                        new
                        {
                            Id = 133,
                            Name = "زاهدان",
                            ProvinceId = 27
                        },
                        new
                        {
                            Id = 134,
                            Name = "چابهار",
                            ProvinceId = 27
                        },
                        new
                        {
                            Id = 135,
                            Name = "ایرانشهر",
                            ProvinceId = 27
                        },
                        new
                        {
                            Id = 136,
                            Name = "خاش",
                            ProvinceId = 27
                        },
                        new
                        {
                            Id = 137,
                            Name = "گرگان",
                            ProvinceId = 28
                        },
                        new
                        {
                            Id = 138,
                            Name = "گنبد",
                            ProvinceId = 28
                        },
                        new
                        {
                            Id = 139,
                            Name = "علی‌آباد",
                            ProvinceId = 28
                        },
                        new
                        {
                            Id = 140,
                            Name = "آق‌قلا",
                            ProvinceId = 28
                        },
                        new
                        {
                            Id = 141,
                            Name = "کلاله",
                            ProvinceId = 28
                        });
                });

            modelBuilder.Entity("Usermanager.Model.Entity.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Usermanager.Model.Entity.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Usermanager.Model.Entity.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "تهران"
                        },
                        new
                        {
                            Id = 2,
                            Name = "البرز"
                        },
                        new
                        {
                            Id = 3,
                            Name = "اصفهان"
                        },
                        new
                        {
                            Id = 4,
                            Name = "فارس"
                        },
                        new
                        {
                            Id = 5,
                            Name = "خراسان رضوی"
                        },
                        new
                        {
                            Id = 6,
                            Name = "آذربایجان شرقی"
                        },
                        new
                        {
                            Id = 7,
                            Name = "آذربایجان غربی"
                        },
                        new
                        {
                            Id = 8,
                            Name = "گیلان"
                        },
                        new
                        {
                            Id = 9,
                            Name = "مازندران"
                        },
                        new
                        {
                            Id = 10,
                            Name = "کرمان"
                        },
                        new
                        {
                            Id = 11,
                            Name = "هرمزگان"
                        },
                        new
                        {
                            Id = 12,
                            Name = "خوزستان"
                        },
                        new
                        {
                            Id = 13,
                            Name = "کردستان"
                        },
                        new
                        {
                            Id = 14,
                            Name = "کرمانشاه"
                        },
                        new
                        {
                            Id = 15,
                            Name = "یزد"
                        },
                        new
                        {
                            Id = 16,
                            Name = "زنجان"
                        },
                        new
                        {
                            Id = 17,
                            Name = "همدان"
                        },
                        new
                        {
                            Id = 18,
                            Name = "قزوین"
                        },
                        new
                        {
                            Id = 19,
                            Name = "قم"
                        },
                        new
                        {
                            Id = 20,
                            Name = "سمنان"
                        },
                        new
                        {
                            Id = 21,
                            Name = "ایلام"
                        },
                        new
                        {
                            Id = 22,
                            Name = "کهگیلویه و بویراحمد"
                        },
                        new
                        {
                            Id = 23,
                            Name = "چهارمحال و بختیاری"
                        },
                        new
                        {
                            Id = 24,
                            Name = "لرستان"
                        },
                        new
                        {
                            Id = 25,
                            Name = "مرکزی"
                        },
                        new
                        {
                            Id = 26,
                            Name = "بوشهر"
                        },
                        new
                        {
                            Id = 27,
                            Name = "سیستان و بلوچستان"
                        },
                        new
                        {
                            Id = 28,
                            Name = "گلستان"
                        });
                });

            modelBuilder.Entity("Usermanager.Model.Entity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accessibility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Usermanager.Model.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("GroupID")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PersonnelNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("GroupID");

                    b.ToTable("People", (string)null);
                });

            modelBuilder.Entity("GroupRole", b =>
                {
                    b.HasOne("Usermanager.Model.Entity.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Usermanager.Model.Entity.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Usermanager.Model.Entity.City", b =>
                {
                    b.HasOne("Usermanager.Model.Entity.Province", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Usermanager.Model.Entity.Group", b =>
                {
                    b.HasOne("Usermanager.Model.Entity.Department", "Department")
                        .WithMany("Groups")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Usermanager.Model.Entity.User", b =>
                {
                    b.HasOne("Usermanager.Model.Entity.City", "City")
                        .WithMany("Users")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Usermanager.Model.Entity.Group", "Group")
                        .WithMany("Users")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("City");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Usermanager.Model.Entity.City", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Usermanager.Model.Entity.Department", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("Usermanager.Model.Entity.Group", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Usermanager.Model.Entity.Province", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
